services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=ironjournal
    volumes:
      - ironjournal_pg_data:/bitnami/postgresql
      - ./database/create.sql:/docker-entrypoint-initdb.d/create.sql

volumes:
  ironjournal_pg_data: