services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=123456
      - POSTGRESQL_DATABASE=ironjournal
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    volumes:
      - ironjournal_pg_data:/bitnami/postgresql
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql

volumes:
  ironjournal_pg_data: